AWSTemplateFormatVersion: "2010-09-09"
Resources:
  TenantTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: "FORMULA_MAIN"
      AttributeDefinitions:
        - AttributeName: "PartitionKey"
          AttributeType: "S"
        - AttributeName: "SortKey"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "PartitionKey"
          KeyType: "HASH"
        - AttributeName: "SortKey"
          KeyType: "RANGE"
      ProvisionedThroughput:
        ReadCapacityUnits: "1"
        WriteCapacityUnits: "1"
