# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Create

on: workflow_dispatch

jobs:
  cfn-create:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # - name: Configure AWS credentials
      #   id: set-credentials
      #   uses: aws-actions/configure-aws-credentials@v1
      #   with:
      #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     aws-region: us-east-1

      - name: Create DynamoDB:Table:Tenants
        id: dynamodb-table-tenants-create
        uses: mdecoleman/cloudformation-changeset@v1
        with:
          method: create
          stack_name: "dynamodb-table-tenants"
          template_file: "./cloudformation/dynamodb-table-tenants.yml"
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: "us-east-1"

      # - name: Create DynamoDB:Table:Tenants
      #   id: dynamodb-table-tenants-create
      #   uses: aws-actions/aws-cloudformation-github-deploy@v1
      #   with:
      #     name: dynamodb-table-tenants
      #     template: ./cloudformation/dynamodb-table-tenants.yml
